ecommerce:
    resource: "@EcommerceBundle/Controller/"
    type:     annotation
    prefix:   /

pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /



# HWIOAuthBundle
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# We override this part of the routing
hwi_oauth_connect:
     resource: "@UtilisateursBundle/Resources/config/routing/connect.xml"
     prefix: /connect

facebook_login:
    path: /connect/check-facebook

utilisateurs:
    resource: "@UtilisateursBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"