services:
    tva:
      class: EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }
    montantTva:
      class: EcommerceBundle\Twig\Extension\montantTvaExtension
      tags:
        - { name: twig.extension }
