services:
    tva:
      class: EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }
    horstaxe:
      class: EcommerceBundle\Twig\Extension\HorstaxeExtension
      tags:
        - { name: twig.extension }
